# Generated by Django 3.2.8 on 2021-11-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_auto_20211130_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstt_name',
            new_name='first_name',
        ),
    ]
